# Generated by Django 3.0.3 on 2020-02-20 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cathegory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cathegory', models.CharField(default='General', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='mainItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_title', models.CharField(max_length=100)),
                ('main_description', models.TextField()),
                ('main_creation_date', models.DateField(auto_now_add=True)),
                ('main_due_date', models.DateField()),
                ('main_cathegory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todoApi.cathegory')),
            ],
        ),
        migrations.CreateModel(
            name='childItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_title', models.CharField(max_length=50)),
                ('child_description', models.TextField()),
                ('child_due_date', models.DateField()),
                ('child_related_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todoApi.mainItem')),
            ],
        ),
    ]
