# Generated by Django 3.0.2 on 2020-02-13 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoApi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cathegory',
            name='cathegory',
            field=models.CharField(default='General', max_length=50),
        ),
    ]
