# Generated by Django 3.0.2 on 2020-02-14 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todoApi', '0003_auto_20200214_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainitem',
            name='main_cathegory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todoApi.cathegory'),
        ),
    ]
